image:
  repository: quay.io/ebigxa/galaxy-hisciap
  tag: 20.01_v3

webHandlers:
  replicaCount: 1

jobHandlers:
  replicaCount: 1

persistence:
  existingClaim: "efs"
#  subPath: "galaxy-pv"
#  minikube:
#    enabled: false
###  existingClaim: galaxy-pvc-nfs

rbac:
  create: true

cloudProvider: aws
awsRegion: eu-west-2

autoDiscovery:
  clusterName: galaxy-eks
  enabled: true

service:
  type: LoadBalancer
#  type: NodePort
#  ports:
  port: 80
#      targetPort: 30700

configs:
  galaxy.yml:
    galaxy:
      admin_users: pmoreno@ebi.ac.uk,jmanning@ebi.ac.uk
      tool_config_file: "/galaxy/server/config/mutable/editable_shed_tool_conf.xml,/galaxy/server/config/tool_conf_ebi-gxa.xml,/galaxy/server/config/tool_conf.xml"
      brand: Galaxy-Training
      allow_user_impersonation: true
      # ^^ MODIFIED ^^
      # vv ORIGINAL vv
      database_connection: postgresql://unused:because@overridden_by_envvar
      integrated_tool_panel_config: "/galaxy/server/config/mutable/integrated_tool_panel.xml"
      sanitize_whitelist_file: "/galaxy/server/config/mutable/sanitize_whitelist.txt"
      shed_tool_config_file: "/galaxy/server/config/mutable/editable_shed_tool_conf.xml"
      tool_dependency_dir: "{{.Values.persistence.mountPath}}/deps"
      job_config_file: "/galaxy/server/config/job_conf.xml"
      containers_resolvers_config_file: "/galaxy/server/config/container_resolvers_conf.xml"
      workflow_schedulers_config_file: "/galaxy/server/config/workflow_schedulers_conf.xml"
      build_sites_config_file: "/galaxy/server/config/build_sites.yml"
      shed_data_manager_config_file: "/galaxy/server/config/mutable/shed_data_manager_conf.xml"
      shed_tool_data_table_config: "/galaxy/server/config/mutable/shed_tool_data_table_conf.xml"
      enable_data_manager_user_view: true
      tool_data_path: "{{.Values.persistence.mountPath}}/tool-data"
      conda_auto_init: false
      smtp_server: smtp.gmail.com
      # If your SMTP server requires a username and password, you can
      # provide them here (password in cleartext here, but if your server
      # supports STARTTLS it will be sent over the network encrypted).
      smtp_username: projectmpsrt@gmail.com
      # If your SMTP server requires a username and password, you can
      # provide them here (password in cleartext here, but if your server
      # supports STARTTLS it will be sent over the network encrypted).
      smtp_password: mwhpqgkmjjfodpwo
      # If your SMTP server requires SSL from the beginning of the
      # connection
      smtp_ssl: true
  job_conf.xml: |
    <job_conf>
        <plugins>
            <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4" />
            <plugin id="k8s" type="runner" load="galaxy.jobs.runners.kubernetes:KubernetesJobRunner">
              <param id="k8s_use_service_account">true</param>
              <param id="k8s_persistent_volume_claims">{{ template "galaxy.pvcname" . }}:{{.Values.persistence.mountPath}}</param>
              <param id="k8s_namespace">{{ .Release.Namespace }}</param>
              <!-- Must be DNS friendly and less than 20 characters -->
              <param id="k8s_galaxy_instance_id">{{ .Release.Name }}</param>
              <param id="k8s_run_as_user_id">101</param>
              <param id="k8s_run_as_group_id">101</param>
              <param id="k8s_fs_group_id">101</param>
              <param id="k8s_supplemental_group_id">101</param>
              <param id="k8s_pull_policy">IfNotPresent</param>
              <param id="k8s_cleanup_job">always</param>
              <param id="k8s_pod_priority_class">{{ include "galaxy.fullname" . }}-job-priority</param>
            </plugin>
        </plugins>
        <destinations default="dynamic-k8s-large">
            <destination id="local" runner="local"/>
            <destination id="dynamic-k8s-dispatcher" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_container_mapper</param>
              <param id="docker_default_container_id">{{ .Values.image.repository }}:{{ .Values.image.tag }}</param>
              <param id="docker_enabled">true</param>
            </destination>
            <destination id="dynamic-k8s-tiny" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_wrapper_tiny</param>
              <param id="no_docker_default_destination_id">local</param>
              <param id="docker_default_container_id">busybox:ubuntu-14.04</param>
              <param id="docker_enabled">true</param>
              <resubmit condition="memory_limit_reached" destination="dynamic-k8s-small"/>
            </destination>
            <destination id="dynamic-k8s-small" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_wrapper_small</param>
              <param id="no_docker_default_destination_id">local</param>
              <param id="docker_default_container_id">busybox:ubuntu-14.04</param>
              <param id="docker_enabled">true</param>
              <resubmit condition="memory_limit_reached" destination="dynamic-k8s-medium"/>
            </destination>
            <destination id="dynamic-k8s-medium" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_wrapper_medium</param>
              <param id="no_docker_default_destination_id">local</param>
              <param id="docker_default_container_id">busybox:ubuntu-14.04</param>
              <param id="docker_enabled">true</param>
              <resubmit condition="memory_limit_reached" destination="dynamic-k8s-large"/>
            </destination>
            <destination id="dynamic-k8s-large" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_wrapper_large</param>
              <param id="no_docker_default_destination_id">local</param>
              <param id="docker_default_container_id">busybox:ubuntu-14.04</param>
              <param id="docker_enabled">true</param>
              <resubmit condition="memory_limit_reached" destination="dynamic-k8s-xlarge"/>
            </destination>
            <destination id="dynamic-k8s-xlarge" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_wrapper_xlarge</param>
              <param id="no_docker_default_destination_id">local</param>
              <param id="docker_default_container_id">busybox:ubuntu-14.04</param>
              <param id="docker_enabled">true</param>
            </destination>
            <destination id="dynamic-k8s-xxlarge" runner="dynamic">
              <param id="type">python</param>
              <param id="function">k8s_wrapper_xxlarge</param>
              <param id="no_docker_default_destination_id">local</param>
              <param id="docker_default_container_id">busybox:ubuntu-14.04</param>
              <param id="docker_enabled">true</param>
            </destination>
            <destination id="salmon_indexer" runner="k8s">
              <param id="docker_repo_override">quay.io</param>
              <param id="docker_owner_override">biocontainers</param>
              <param id="docker_image_override">mulled-v2-fb4d08d60ecf9b9ad7391e52c2cefda3ec2d3078</param>
              <param id="docker_tag_override">21cc1ec220153ab2a131b0ad2d920f7094b4d076-0</param>
              <param id="docker_enabled">true</param>
            </destination>
        </destinations>
        <tools>
            <tool id="toolshed.g2.bx.psu.edu/repos/iuc/data_manager_salmon_index_builder/salmon_index_builder_data_manager/0.11.3" destination="salmon_indexer"/>
        </tools>
        <limits>
            <limit type="registered_user_concurrent_jobs">5</limit>
            <limit type="anonymous_user_concurrent_jobs">2</limit>
        </limits>
    </job_conf>
  tool_conf_ebi-gxa.xml: |
    <?xml version='1.0' encoding='utf-8'?>
    <toolbox>
    <label id="single_cell" text="Single Cell RNA-Seq Tools"/>
    <section id="hca_sc_get-scrna" name="Get scRNAseq data">
     </section>
     <section id="hca_sc_seurat_tools" name="Seurat">
     </section>
     <section id="hca_sc_sc3_tools" name="SC3">
     </section>
     <section id="hca_sc_scanpy_tools" name="Scanpy">
     </section>
     <section id="hca_sc_monocle3_tools" name="Monocl3">
     </section>
     <section id="hca_sc_scmap_tools" name="SCMap">
     </section>
     <section id="hca_sc_sccaf_tools" name="SCCAF">
     </section>
     <section id="hca_sc_utils_viz" name="Single Cell Utils and Viz">
     </section>
     <label id="rna_seq_label" text="Bulk RNA-Seq Tools"/>
     <section id="rna_seq" name="RNA-Seq">
     </section>
     <section id="gxa_util" name="Util">
     </section>
    </toolbox>

jobs:
  rules:
    resource_bins.yaml: |
      ---
      resource_bins:
        tiny:
          requests_cpu: 0.1
          limits_cpu: 0.5
          requests_memory: 0.3
          limits_memory: 0.6
          dest_id: "dynamic-k8s-tiny"
        small:
          requests_cpu: 0.4
          limits_cpu: 0.8
          requests_memory: 1
          limits_memory: 2
          dest_id: "dynamic-k8s-small"
        medium:
          requests_cpu: 0.7
          limits_cpu: 2
          requests_memory: 2
          limits_memory: 4
          dest_id: "dynamic-k8s-medium"
        large:
          requests_cpu: 1.5
          limits_cpu: 4
          requests_memory: 3
          limits_memory: 6
          dest_id: "dynamic-k8s-large"
        xlarge:
          requests_cpu: 4
          limits_cpu: 8
          requests_memory: 8
          limits_memory: 16
          dest_id: "dynamic-k8s-xlarge"
        xxlarge:
          requests_cpu: 4
          limits_cpu: 8
          requests_memory: 16
          limits_memory: 32
          dest_id: "dynamic-k8s-xxlarge"
      unit_suffix:
        memory: "Gi"
    tools2container.yaml: |
      global:
        docker_repo:
        max_pod_retrials: 3
      assignment:
        - tools_id:
           - my_tool:
              docker_repo_override: quay.io
              docker_owner_override: ebigxa
              docker_image_override: r-seurat-scripts
              docker_tag_override: 0.0.1--0
              max_pod_retrials: 3
        #- tools_id:
        #   - ucsc-cell-browser
        #       docker_repo_override: quay.io
        #       docker_owner_override: ebigxa
        #       docker_image_override: ucsc-cell-browser
        #       docker_tag_override: 0.25--0
        #       max_pod_retrials: 3

extraFileMappings: Null

ingress:
  enabled: false

influxdb:
  enabled: false

proftpd:
  enabled: false
  service:
    type: NodePort

rbac:
  enabled: true

postgresql:
  galaxyDatabasePassword: changeme
  postgresqlPassword: changeme
  postgresqlPostgresPassword: changeme
  persistence:
    existingClaim: "postgres-pvc"
